path_classifiers:
  test:
    - tests
extraction:
  cpp:
    prepare:
      packages:
        - clang-12
        - llvm-12-dev
        - llvm-12-runtime
        - libtbb2
        - ninja-build
    configure:
      command:
        - cmake -GNinja -H. -Bbuild -DCMAKE_CXX_COMPILER=/usr/bin/clang++-12 -DCMAKE_BUILD_TYPE=Debug
    index:
      build_command: cmake --build ./build
