path_classifiers:
  test:
    - tests
extraction:
  cpp:
    prepare:
      packages:
        - ccache
        - ninja-build
      script:
        - add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - apt update && apt install -y gcc-11 g++-11
    configure:
      command:
        - cmake -GNinja -H. -Bbuild -DCMAKE_CXX_COMPILER=/usr/bin/g++-11 -DCMAKE_BUILD_TYPE=Debug
    index:
      build_command: cmake --build ./build
